from dataclasses import dataclass, field
from typing import Any

from tracking.tracker import Track


@dataclass
class TrackState:
    """
    Persistent state for one tracked object.

    track_id:
        Temporal identity generated by ByteTrack.

    detection_id:
        Frame-local identity generated by Member 1.
        It may be None if the tracker cannot associate
        the current track with a detector output.
    """

    track_id: int
    detection_id: str | None

    class_id: int
    class_name: str

    confidence: float
    bbox_xyxy: list[float]

    center: tuple[float, float]
    foot_point: tuple[float, float]

    first_seen_frame: int
    last_seen_frame: int

    # Number of frames in which this track has been observed.
    frame_count: int = 1

    # Recent center-position history.
    history: list[tuple[float, float]] = field(
        default_factory=list
    )

    # Recent foot-point history.
    foot_history: list[tuple[float, float]] = field(
        default_factory=list
    )

    # Current zone assigned by the zone engine.
    current_zone: str | None = None

    # Previous zone, useful for detecting entry/exit.
    previous_zone: str | None = None

    def update(
        self,
        track: Track,
        frame_index: int,
        max_history: int = 30,
    ) -> None:
        """
        Update persistent state from the latest tracker output.
        """

        self.detection_id = track.detection_id

        self.class_id = track.class_id
        self.class_name = track.class_name

        self.confidence = track.confidence
        self.bbox_xyxy = list(track.bbox_xyxy)

        self.center = track.center
        self.foot_point = track.foot_point

        self.last_seen_frame = frame_index
        self.frame_count += 1

        self.history.append(track.center)
        self.foot_history.append(track.foot_point)

        # Keep only the most recent positions.
        if len(self.history) > max_history:
            self.history = self.history[-max_history:]

        if len(self.foot_history) > max_history:
            self.foot_history = self.foot_history[-max_history:]

    def set_zone(
        self,
        zone_id: str | None,
    ) -> None:
        """
        Update zone information.

        The previous zone is preserved so downstream logic
        can determine transitions such as:

            None -> zone_a
            zone_a -> zone_b
            zone_b -> None
        """

        self.previous_zone = self.current_zone
        self.current_zone = zone_id

    def to_dict(self) -> dict[str, Any]:
        """
        Convert state into JSON/database-friendly data.
        """

        return {
            "track_id": self.track_id,
            "detection_id": self.detection_id,
            "class_id": self.class_id,
            "class_name": self.class_name,
            "confidence": self.confidence,
            "bbox_xyxy": list(self.bbox_xyxy),
            "center": list(self.center),
            "foot_point": list(self.foot_point),
            "first_seen_frame": self.first_seen_frame,
            "last_seen_frame": self.last_seen_frame,
            "frame_count": self.frame_count,
            "history": [
                list(point)
                for point in self.history
            ],
            "foot_history": [
                list(point)
                for point in self.foot_history
            ],
            "current_zone": self.current_zone,
            "previous_zone": self.previous_zone,
        }


class TrackStateManager:
    """
    Maintains persistent state for currently tracked objects.

    All state is keyed by (camera_id, track_id) to prevent
    cross-camera identity leakage.
    """

    def __init__(
        self,
        max_history: int = 30,
        max_missing_frames: int = 30,
    ):
        if max_history <= 0:
            raise ValueError(
                "max_history must be greater than 0"
            )

        if max_missing_frames < 0:
            raise ValueError(
                "max_missing_frames cannot be negative"
            )

        self.max_history = max_history
        self.max_missing_frames = max_missing_frames

        self.states: dict[
            tuple[str | None, int], TrackState
        ] = {}

    def update(
        self,
        tracks: list[Track],
        frame_index: int,
        camera_id: str | None = None,
    ) -> list[TrackState]:
        """
        Update persistent state from the current frame.

        Returns only states that were observed in this frame.
        """

        if frame_index < 0:
            raise ValueError(
                "frame_index cannot be negative"
            )

        active_keys: set[
            tuple[str | None, int]
        ] = set()

        for track in tracks:

            track_id = track.track_id

            # Ignore invalid tracker IDs.
            if track_id < 0:
                continue

            key = (camera_id, track_id)
            active_keys.add(key)

            # ---------------------------------------------
            # New track
            # ---------------------------------------------

            if key not in self.states:

                state = TrackState(
                    track_id=track_id,
                    detection_id=track.detection_id,
                    class_id=track.class_id,
                    class_name=track.class_name,
                    confidence=track.confidence,
                    bbox_xyxy=list(track.bbox_xyxy),
                    center=track.center,
                    foot_point=track.foot_point,
                    first_seen_frame=frame_index,
                    last_seen_frame=frame_index,
                    frame_count=1,
                    history=[track.center],
                    foot_history=[track.foot_point],
                )

                self.states[key] = state

            # ---------------------------------------------
            # Existing track
            # ---------------------------------------------

            else:

                self.states[key].update(
                    track=track,
                    frame_index=frame_index,
                    max_history=self.max_history,
                )

        # ---------------------------------------------
        # Remove tracks missing for too long
        # ---------------------------------------------

        expired_keys: list[
            tuple[str | None, int]
        ] = []

        for key, state in self.states.items():

            if key in active_keys:
                continue

            missing_frames = (
                frame_index
                - state.last_seen_frame
            )

            if missing_frames > self.max_missing_frames:
                expired_keys.append(key)

        for key in expired_keys:
            del self.states[key]

        # ---------------------------------------------
        # Return states observed in this frame.
        # ---------------------------------------------

        return [
            self.states[key]
            for key in active_keys
            if key in self.states
        ]

    def get(
        self,
        track_id: int,
        camera_id: str | None = None,
    ) -> TrackState | None:
        """
        Retrieve one tracked object's state.
        """

        return self.states.get(
            (camera_id, track_id)
        )

    def remove(
        self,
        track_id: int,
        camera_id: str | None = None,
    ) -> None:
        """
        Explicitly remove a track state.
        """

        self.states.pop(
            (camera_id, track_id),
            None,
        )

    def reset(self) -> None:
        """
        Clear all persistent tracking state.
        """

        self.states.clear()

    def to_dict(self) -> dict[str, Any]:
        """
        Export all currently stored states.
        """

        return {
            f"{cam}:{track_id}": state.to_dict()
            for (cam, track_id), state
            in self.states.items()
        }
