from dataclasses import dataclass
from typing import Any

import numpy as np
import supervision as sv

try:
    from trackers import ByteTrackTracker
except ImportError:
    ByteTrackTracker = None  # type: ignore[assignment, misc]

from tracking.adapter import Detection


@dataclass
class Track:
    """
    A temporally tracked detection.

    detection_id:
        Member 1's frame-local detection identifier.

    track_id:
        Member 2 / ByteTrack's temporal identity.

    These IDs are intentionally separate.
    """

    track_id: int
    detection_id: str | None
    class_id: int
    class_name: str
    confidence: float
    bbox_xyxy: list[float]
    center: tuple[float, float]
    foot_point: tuple[float, float]
    confirmed: bool = True

    def to_dict(self) -> dict[str, Any]:
        return {
            "track_id": self.track_id,
            "detection_id": self.detection_id,
            "class_id": self.class_id,
            "class_name": self.class_name,
            "confidence": self.confidence,
            "bbox_xyxy": self.bbox_xyxy,
            "center": list(self.center),
            "foot_point": list(self.foot_point),
            "confirmed": self.confirmed,
        }


class TrackerWrapper:

    def __init__(
        self,
        track_activation_threshold: float = 0.25,
        lost_track_buffer: int = 30,
        minimum_iou_threshold: float = 0.8,
        minimum_consecutive_frames: int = 1,
        frame_rate: int = 30,
    ):
        """
        Initialize ByteTrack.

        ByteTrack owns track_id generation.
        """

        if ByteTrackTracker is None:
            raise ImportError(
                "ByteTrackTracker not available. "
                "Install the 'trackers' package or "
                "run from the tracking/ directory."
            )

        self.tracker = ByteTrackTracker(
            track_activation_threshold=track_activation_threshold,
            lost_track_buffer=lost_track_buffer,
            minimum_iou_threshold=minimum_iou_threshold,
            minimum_consecutive_frames=minimum_consecutive_frames,
            frame_rate=frame_rate,
        )

    def update(
        self,
        detections: list[Detection],
    ) -> list[Track]:
        """
        Update tracker with one frame of detections.

        Input:
            Member 2 Detection objects.

        Output:
            Track objects containing:

                detection_id
                track_id
                class information
                bbox
                center
                foot point

        detection_id remains the Member 1 identifier.
        track_id is generated by ByteTrack.
        """

        if not detections:
            # Important:
            # We still update ByteTrack with an empty detection
            # set so its internal lifecycle can process lost tracks.
            empty_detections = sv.Detections.empty()

            self.tracker.update(empty_detections)

            return []

        xyxy = np.array(
            [
                detection.bbox_xyxy
                for detection in detections
            ],
            dtype=np.float32,
        )

        confidence = np.array(
            [
                detection.confidence
                for detection in detections
            ],
            dtype=np.float32,
        )

        class_id = np.array(
            [
                detection.class_id
                for detection in detections
            ],
            dtype=int,
        )

        sv_detections = sv.Detections(
            xyxy=xyxy,
            confidence=confidence,
            class_id=class_id,
        )

        tracked = self.tracker.update(
            sv_detections
        )

        results: list[Track] = []

        if tracked.tracker_id is None:
            return results

        for i in range(len(tracked)):

            raw_track_id = tracked.tracker_id[i]

            if raw_track_id is None:
                continue

            track_id = int(raw_track_id)

            # ByteTrack uses -1 for a track that is not
            # currently confirmed.
            if track_id < 0:
                continue

            # -------------------------------------------------
            # Tracker bounding box
            # -------------------------------------------------

            bbox = [
                float(value)
                for value in tracked.xyxy[i].tolist()
            ]

            x1, y1, x2, y2 = bbox

            center = (
                (x1 + x2) / 2.0,
                (y1 + y2) / 2.0,
            )

            foot_point = (
                (x1 + x2) / 2.0,
                y2,
            )

            # -------------------------------------------------
            # Tracker metadata
            # -------------------------------------------------

            if tracked.confidence is not None:
                confidence_value = float(
                    tracked.confidence[i]
                )
            else:
                confidence_value = 0.0

            if tracked.class_id is not None:
                class_value = int(
                    tracked.class_id[i]
                )
            else:
                class_value = 0

            # -------------------------------------------------
            # Associate ByteTrack result with the original
            # Member 1 detection.
            # -------------------------------------------------

            detection = self._match_detection(
                bbox=bbox,
                class_id=class_value,
                detections=detections,
            )

            if detection is not None:
                detection_id = detection.detection_id
                class_name = detection.class_name
            else:
                # The track can exist even when we cannot
                # confidently map it back to the current
                # Member 1 detection.
                detection_id = None
                class_name = "unknown"

            results.append(
                Track(
                    track_id=track_id,
                    detection_id=detection_id,
                    class_id=class_value,
                    class_name=class_name,
                    confidence=confidence_value,
                    bbox_xyxy=bbox,
                    center=center,
                    foot_point=foot_point,
                    confirmed=True,
                )
            )

        return results

    @staticmethod
    def _match_detection(
        bbox: list[float],
        class_id: int,
        detections: list[Detection],
    ) -> Detection | None:
        """
        Match a ByteTrack output back to one of the original
        Member 1 detections.

        Matching priority:

            1. Same class + highest IoU
            2. Same class + closest center

        This is considerably safer than blindly selecting the
        nearest detection.
        """

        if not detections:
            return None

        candidates = [
            detection
            for detection in detections
            if detection.class_id == class_id
        ]

        if not candidates:
            candidates = detections

        # -----------------------------------------------------
        # First: IoU matching
        # -----------------------------------------------------

        best_detection: Detection | None = None
        best_iou = 0.0

        for detection in candidates:

            iou = TrackerWrapper._calculate_iou(
                bbox,
                detection.bbox_xyxy,
            )

            if iou > best_iou:
                best_iou = iou
                best_detection = detection

        # A meaningful overlap is the strongest association.
        if best_detection is not None and best_iou > 0.1:
            return best_detection

        # -----------------------------------------------------
        # Second: center-distance fallback
        # -----------------------------------------------------

        x1, y1, x2, y2 = bbox

        tracked_center_x = (
            x1 + x2
        ) / 2.0

        tracked_center_y = (
            y1 + y2
        ) / 2.0

        closest_detection: Detection | None = None
        closest_distance = float("inf")

        for detection in candidates:

            detection_center = detection.center

            dx = (
                detection_center[0]
                - tracked_center_x
            )

            dy = (
                detection_center[1]
                - tracked_center_y
            )

            distance = (
                dx * dx
                + dy * dy
            )

            if distance < closest_distance:
                closest_distance = distance
                closest_detection = detection

        return closest_detection

    @staticmethod
    def _calculate_iou(
        bbox_a: list[float],
        bbox_b: list[float],
    ) -> float:
        """
        Calculate intersection-over-union between two
        xyxy bounding boxes.
        """

        ax1, ay1, ax2, ay2 = bbox_a
        bx1, by1, bx2, by2 = bbox_b

        intersection_x1 = max(
            ax1,
            bx1,
        )

        intersection_y1 = max(
            ay1,
            by1,
        )

        intersection_x2 = min(
            ax2,
            bx2,
        )

        intersection_y2 = min(
            ay2,
            by2,
        )

        intersection_width = max(
            0.0,
            intersection_x2 - intersection_x1,
        )

        intersection_height = max(
            0.0,
            intersection_y2 - intersection_y1,
        )

        intersection_area = (
            intersection_width
            * intersection_height
        )

        area_a = max(
            0.0,
            ax2 - ax1,
        ) * max(
            0.0,
            ay2 - ay1,
        )

        area_b = max(
            0.0,
            bx2 - bx1,
        ) * max(
            0.0,
            by2 - by1,
        )

        union_area = (
            area_a
            + area_b
            - intersection_area
        )

        if union_area <= 0.0:
            return 0.0

        return intersection_area / union_area

    def reset(self):
        """
        Reset ByteTrack's internal tracking state.
        """

        self.tracker.reset()
